---
name: mcdp-language
displayName: MCDP Language
description: Syntax highlighting for the MCDP modeling language
version: 1.3.7
publisher: zupermind
engines:
  vscode: ^1.0.0
categories:
- Programming Languages
contributes:
  languages:
  - id: mcdp
    aliases:
    - MCDP
    - mcdp
    extensions:
    - .mcdp
    - .mcdp_template
    - .mcdp_value
    - .mcdp_poset
    - .mcdp_interface
    - .mcdp_primitivedp
    configuration: ./language-configuration.json
  grammars:
  - language: mcdp
    scopeName: source.mcdp
    path: ./syntaxes/mcdp.tmLanguage.json
  themes:
  - label: MCDP Theme (dark)
    uiTheme: vs-dark
    path: ./themes/mcdp-color-theme-dark.json
license: MIT
repository:
  type: git
  url: "https://github.com/zupermind/mcdp-vscode.git"
bugs:
  url: "https://github.com/zupermind/mcdp-vscode/issues"
homepage: "https://github.com/zupermind/mcdp-vscode#readme"
keywords:           # Helps with marketplace discovery
- mcdp
- syntax
- highlighting
author:            # Optional but recommended
  name: Andrea Censi
  email: andrea@zupermind.com
